NurburgKind: SERVICE
Name: test-service
Replicas: 2
Port: 9000
MemoryMiB: 256
CPU: 1
Env:
  TEST_ENV_VAR: VALUE
---
NurburgKind: POSTGRES
Name: postgres-test
---
NurburgKind: K6DBSEEDER
Name: postgres-seeder
File: seeder.js
---
NurburgKind: K6LOAD
Name: load-test
File: load.js
